; ANPR Video Monitor Configuration
; source: 0, rtsp://... або d:\video.mp4
; autostart_os_and_play: true / false
; view_plate_time: час збереження номера на екрані (с)
; delete_older_days: видаляти файли старше зазначених днів
; min_percent_to_save: мінімальна точність розпізнавання для збереження (%)
; sleep_time_after_save: таймаут паузи після вдалого визначення номера (с)
; rect_scale_plate: масштаб номера у правому верхньому кутку (базове 5.0)
; rect_scale_user_top, left, width, height: геометрія вікна виділення

[SETTINGS]
source = d:\Skalatskiy\Develop\Projects\Get_Number\_video_\YTDown.com_YouTube_Media_DGoQzuuL5CA_001_1080p.mp4
autostart_os_and_play = true
view_plate_time = 10
delete_older_days = 10.0
min_percent_to_save = 90
sleep_time_after_save = 5.0
rect_scale_plate = 10.0
rect_scale_user_top = 80
rect_scale_user_left = 11
rect_scale_user_width = 583
rect_scale_user_height = 406

