; ANPR & Face Video Monitor Configuration
; plates_on: true / false (фіксація номерних знаків)
; faces_on: true / false (фіксація облич)
; face_min_similarity: поріг схожості векторів облич (0.7 = 70%)
; face_det_thresh: поріг детекції облич
; source: 0, rtsp://... або d:\video.mp4
; autostart_os_and_play: true / false
; view_plate_time: час збереження номера на екрані (с)
; delete_older_days: видаляти файли старше зазначених днів
; min_percent_to_save: мінімальна точність розпізнавання для збереження (%)
; sleep_time_after_save: таймаут ігнорування дублікатів того самого номера (с)
; rect_scale_plate: масштаб номера у правому верхньому кутку (базове 5.0)
; rect_scale_user_top, left, width, height: геометрія вікна виділення

[SETTINGS]
source = d:\Projects\Antigravity\projects\Get-plate-number-from-camera\_VIDEO_\YTDown.com_YouTube_Media_dQ2AMRjNd7s_Качки-хотели-САМОУТВЕРДИТЬСЯ-НО-ANATOLY-Gym-Prank_001_1080p.mp4
autostart_os_and_play = false
plates_on = true
faces_on = true
face_min_similarity = 0.7
face_det_thresh = 0.45
view_plate_time = 30
delete_older_days = 1
min_percent_to_save = 80
sleep_time_after_save = 5.0
rect_scale_plate = 5.0
rect_scale_user_top = 20
rect_scale_user_left = 20
rect_scale_user_width = 360
rect_scale_user_height = 240

