; ANPR Video Monitor Configuration
; source: 0, rtsp://... або d:\video.mp4
; autostart: true / false
; screenshots: true / false (знімки кожні 10 с)
; plate_timeout: час збереження номера на екрані (за замовчуванням 30с)
; delete_older: видаляти файли старше вказаних годин (перевірка раз на годину)

[SETTINGS]
source = _video_\YTDown.com_YouTube_Media_DGoQzuuL5CA_001_1080p.mp4
autostart = true
screenshots = true
plate_timeout = 30
delete_older = 24

